### ISSUE TITLE
[ISSUE] "Unable to find vuetorrent installation" When checking on the curl ip:port/ping

### ISSUE THREAD

**Issue by PingoLeon** [VueTorrent/vuetorrent-backend#42]
Hi ! 

I've been using VueTorrent for a while and I love it. However, having a backend was a miss for me since I don't want to re-set every vuetorrent settings on each machine (If I understood the purpose of this project right).

Here is my docker-compose file : 
```
gluetun:

    image: qmcgaw/gluetun:latest

    ports:
      - 6881:6881 #QBit Torrent
      - 6881:6881/udp #QBit Torrent
      - 8080:8080 #QBit WebUI

    environment:

      - FIREWALL_INPUT_PORTS=8080,8191,6881

    networks:
      Network:
        ipv4_address: 172.19.0.10

    [other unrelated gluetun settings]

  Qbit:
    image: lscr.io/linuxserver/qbittorrent:libtorrentv1

    environment:
      - WEBUI_PORT=8080
      - PUID=1000
      - PGID=1000
      - DOCKER_MODS=ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest

    network_mode: service:gluetun
    
    [other unrelated settings]

  Vuetorrent-backend:
  
    image: ghcr.io/vuetorrent/vuetorrent-backend:latest
    
    container_name: Vuetorrent-backend
    
    volumes:
      - "/config/qbittorrent/vuetorrent:/config"
    
    ports:
      - 3034:3034
      
    environment:
      - CONFIG_PATH=/config

      - PORT=3034

      - QBIT_BASE=http://172.19.0.10:8080 #QBit adress through gluetun

      - RELEASE_TYPE=stable
    
    restart: always
 
```
Now, when i input `http://localhost:3034` in VueTorrent settings, it seems to work since it doesn't prompt "Back-end Unreachable"

Please note that Qbittorrent container runs inside gluetun's network, so we use here the adress of gluetun to communicate with it : 172.19.0.10

However, when I then tried to ping the server using curl, I get this error message : 
```
~$ curl http://LAN_IP_ADRESS:3034/ping
Unable to find vuetorrent installation, please make sure it is accessible at /vuetorrent/public
```

I don't understand since Vuetorrent is loaded just as it should be through Docker mods, and when looking inside qbit container, we do see vuetorrent folder

Newt when I try to access vuetorrent through the back-end, using LAN:3034, first it prompts the vuetorrentUI for the login page, and advert "Backend Unreachable" and "Login failed!
Error code: 404 (Unable to find vuetorrent installation, please make sure it is accessible at /vuetorrent/public)" Vue Alert
