### ISSUE TITLE
[REQUEST] Provide a Docker Compose example with Gluetun

### ISSUE THREAD

**Issue by seth100** [VueTorrent/vuetorrent-backend#44]
Hi,

I use Gluetun and I was not able to configure correctly the backend with my existing Gluetu + qBittorrent stack configuration, could you please update the Wiki providing a working example?

Thanks

**Comment by Larsluph** [comment]
I don't use gluetun. Please provide your old and new configuration so that I can assist you in the migration process.

**Comment by seth100** [comment]
E.g.

```yml
services:
  gluetun:
    image: qmcgaw/gluetun:v3
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=
      - VPN_ENDPOINT_PORT=
      - VPN_DNS_ADDRESS=
      - WIREGUARD_PRIVATE_KEY=
      - WIREGUARD_PUBLIC_KEY=
      - WIREGUARD_ADDRESSES=
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER=
      - HTTP_CONTROL_SERVER_ADDRESS=:8123
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /data/gluetun:/gluetun
    ports:
      - 8033:8123/tcp # Gluetun API
      # - 8225:8225 # qbittorrent
      - 8226:3001 # vuetorrent-backend
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - WEBUI_PORT=8225
    volumes:
      - /data/qbittorrent/config:/config
      - /downloads:/downloads
      # - /data/qbittorrent/themes:/themes
    restart: unless-stopped
    network_mode: 'service:gluetun'

  vuetorrent-backend:
    image: ghcr.io/vuetorrent/vuetorrent-backend:latest
    container_name: vuetorrent-backend
    environment:
      - CONFIG_PATH=/config
      - PORT=3001
      - QBIT_BASE=http://qbittorrent:8225
      - VUETORRENT_PATH=/vuetorrent
    volumes:
      - '/data/qbittorrent/themes/vuetorrent/vuetorrent-backend/config:/config'
      - '/data/qbittorrent/themes/vuetorrent/theme:/vuetorrent'
    restart: unless-stopped
    network_mode: 'service:gluetun'
```

when running http://localhost:8226 I try to login and I get `Unable to find vuetorrent installation, please make sure it is accessible at /vuetorrent/public`

**Comment by Larsluph** [comment]
This looks like the same as #42, I just pushed a fix, try again with 2.0.2

**Comment by seth100** [comment]
> This looks like the same as #42, I just pushed a fix, try again with 2.0.2

it works now thanks, but then I had to make some more changes:

```yml
gluetun:
    ...
    ports:
      - 8033:8123/tcp # Gluetun API
      - 8226:8225 # vuetorrent-backend
     
vuetorrent-backend:
    ...
    environment:
      - PORT=8225
      - QBIT_BASE=http://localhost:8225
```

to fix other issues and now I get `Login failed! Error code: 431 ()` that I cannot undestand:

![test](https://github.com/user-attachments/assets/3f7598d8-519e-4ba7-bd6b-4331d30fd1d5)
