### ISSUE TITLE
[ISSUE] Cannot start container as non-root user

### ISSUE THREAD

**Issue by paulora2405** [VueTorrent/vuetorrent-backend#53]
I'm currently trying to migrate from 1.x to 2.x, my `compose.yaml` looks something like:

```yaml
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - UMASK_SET=$UMASK
      - PUID=$MEDIA_UID
      - PGID=$MEDIA_UID
      - TZ=$TIMEZONE
      - WEBUI_PORT=7777
      - TORRENTING_PORT=6881
    volumes:
      - ./data/qbittorrent:/config
      - $HDD1_PATH/data/downloads:/data/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp

  qbit-backend:
    container_name: qbit-backend
    image: ghcr.io/vuetorrent/vuetorrent-backend:latest
    restart: unless-stopped
    user: "$MEDIA_UID:$MEDIA_UID"
    environment:
      - QBIT_BASE=http://qbittorrent:7777
      - DISABLE_AUTH=true
      - CONFIG_PATH=/config
      - RELEASE_TYPE=stable
      - PORT=7777
    volumes:
      - ./data/qbit-backend:/config
    expose:
      - 7777
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.qbit-backend.loadbalancer.server.port=7777'
      - 'traefik.http.routers.qbit-backend.rule=Host(`qbit.${MY_DOMAIN}`)'
      - 'traefik.http.routers.qbit-backend.entryPoints=websecure'
      - 'traefik.http.routers.qbit-backend.middlewares=authentik@docker'
```

I have a .env file that sets the `$MEDIA_UID` to the appropriate value, but I think an issue arises when trying to start the container as non-root, because it logs the following:

```log
Checking for updates...
node:fs:1373
  const result = binding.mkdir(
                         ^

Error: EACCES: permission denied, mkdir '/vuetorrent'
    at Object.mkdirSync (node:fs:1373:26)
    at downloadUpdate (file:///app/src/routines/update.js:89:8)
    at checkForUpdate (file:///app/src/routines/update.js:133:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server.<anonymous> (file:///app/src/index.js:53:15) {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/vuetorrent'
}

Node.js v21.7.3
```

When I remove the `user: ...` key from the yaml, it seems to work correctly, but I would prefer maintaining my current pattern of not running root containers, if possible.
