### ISSUE TITLE
431 Error when using the backend with gluetun as the exit container

### ISSUE THREAD

**Issue by markgyoni** [VueTorrent/vuetorrent-backend#62]
Hey, I'm trying to use the rewritten backend with gluetun but I'm getting the 431 Request Header Fields Too Large error but only on the  "version" and "login requests" in the browser,

```
gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8000:8000/tcp
      - 51820:51820/udp
      - 51821:51821/tcp
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080  # For vuetorrent-backend
    restart: unless-stopped
    volumes:
      - ./config/gluetun:/gluetun
    labels:
      - traefik, etc
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=
      - WIREGUARD_ADDRESSES=
      - SERVER_CITIES=
      - PUID=0
      - PGID=0

  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent
    restart: unless-stopped
    network_mode: service:gluetun
    volumes:
      - ./config/qbittorrent:/config
      - ./storage/downloads:/downloads
      - ./vuetorrent:/ui
    environment:
      - PUID=0
      - PGID=0
    depends_on:
      - gluetun
      - vuetorrent-backend
  
  vuetorrent-backend:
    image: ghcr.io/vuetorrent/vuetorrent-backend:latest
    container_name: vuetorrent-backend
    network_mode: service:gluetun
    restart: unless-stopped
    environment:
      - QBIT_BASE=http://localhost:8080
      - PORT=8080
      - RELEASE_TYPE=stable
      - UPDATE_VT_CRON=0 * * * *
      - CONFIG_PATH=/config
    volumes:
      - ./config/vuetorrent-backend:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.vuetorrent-backend.entrypoints=web
      - traefik.http.routers.vuetorrent-backend.rule=Host(`qbt.media.markgyoni.dev`) && PathPrefix(`/server`)
    depends_on:
      - gluetun
```

Using nginx as top level reverse proxy and traefik between containers. I tried this in nginx with no results:
`large_client_header_buffers 4 32k;`

Thanks in advance!
